"""
Email service — sends meeting summary via SMTP.
Works with Gmail (app password), SendGrid SMTP relay, or any SMTP server.
"""

import os
import smtplib
from email.mime.multipart import MIMEMultipart
from email.mime.text import MIMEText
from email.mime.application import MIMEApplication


SMTP_HOST     = os.getenv("SMTP_HOST", "smtp.gmail.com")
SMTP_PORT     = int(os.getenv("SMTP_PORT", "587"))
SMTP_USER     = os.getenv("SMTP_USER", "")
SMTP_PASSWORD = os.getenv("SMTP_PASSWORD", "")
FROM_EMAIL    = os.getenv("FROM_EMAIL", SMTP_USER)


def _build_html(meeting_data: dict) -> str:
    title    = meeting_data.get("title", "Meeting")
    summary  = (meeting_data.get("summary") or "").replace("\n", "<br>")
    actions  = meeting_data.get("action_items") or []
    keywords = meeting_data.get("keywords") or []

    action_html = "".join(f"<li>{a}</li>" for a in actions) if actions else "<li>None identified</li>"
    keyword_html = ", ".join(f"<code>{k}</code>" for k in keywords[:12])

    return f"""
    <html><body style="font-family:Arial,sans-serif;max-width:640px;margin:0 auto;color:#333">
      <div style="background:#111;padding:24px 32px;border-radius:8px 8px 0 0">
        <h1 style="color:#fff;margin:0;font-size:1.3rem">Meeting Summary</h1>
        <p style="color:#aaa;margin:4px 0 0">{title}</p>
      </div>
      <div style="border:1px solid #eee;border-top:none;padding:28px 32px;border-radius:0 0 8px 8px">
        <h2 style="font-size:1rem;border-bottom:2px solid #f0f0f0;padding-bottom:8px">Summary</h2>
        <p style="line-height:1.8;color:#555">{summary}</p>
        <h2 style="font-size:1rem;border-bottom:2px solid #f0f0f0;padding-bottom:8px;margin-top:24px">Action Items</h2>
        <ul style="line-height:2;color:#555">{action_html}</ul>
        {'<h2 style="font-size:1rem;border-bottom:2px solid #f0f0f0;padding-bottom:8px;margin-top:24px">Key Topics</h2><p style="color:#555">' + keyword_html + '</p>' if keywords else ''}
        <hr style="border:none;border-top:1px solid #eee;margin:28px 0">
        <p style="font-size:.8rem;color:#aaa">Generated by AI Meeting Summarizer</p>
      </div>
    </body></html>
    """


def send_summary_email(
    to_emails: list[str],
    meeting_data: dict,
    pdf_bytes: bytes | None = None,
) -> None:
    """
    Send meeting summary to one or more recipients.
    Optionally attach the PDF export.
    """
    if not SMTP_USER or not SMTP_PASSWORD:
        raise RuntimeError("SMTP credentials not configured. Set SMTP_USER and SMTP_PASSWORD in .env")

    title = meeting_data.get("title", "Meeting")
    msg = MIMEMultipart("mixed")
    msg["Subject"] = f"Meeting Summary: {title}"
    msg["From"]    = FROM_EMAIL
    msg["To"]      = ", ".join(to_emails)

    html_part = MIMEText(_build_html(meeting_data), "html")
    msg.attach(html_part)

    if pdf_bytes:
        pdf_part = MIMEApplication(pdf_bytes, _subtype="pdf")
        safe_title = "".join(c if c.isalnum() or c in " _-" else "_" for c in title)
        pdf_part.add_header("Content-Disposition", "attachment", filename=f"{safe_title}.pdf")
        msg.attach(pdf_part)

    with smtplib.SMTP(SMTP_HOST, SMTP_PORT) as server:
        server.ehlo()
        server.starttls()
        server.login(SMTP_USER, SMTP_PASSWORD)
        server.sendmail(FROM_EMAIL, to_emails, msg.as_string())
